#!/bin/bash

# lunarvim
LV_BRANCH=rolling bash <(curl -s https://raw.githubusercontent.com/lunarvim/lunarvim/rolling/utils/installer/install.sh) --no-install-dependencies

npm i -g bash-language-server

# dotfiles
cd ~/dotfiles && ./install.sh lvim
